name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # may contain uppercase

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Normalize image name to lowercase
        id: repo
        run: |
          echo "name=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Install cosign (non-PR)
        if: github.event_name != 'pull_request'
        run: |
          set -euo pipefail
          COSIGN_VERSION="v2.2.4"
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64) COSIGN_ARCH=amd64 ;;
            aarch64) COSIGN_ARCH=arm64 ;;
            *) echo "Unsupported arch: $ARCH"; exit 1 ;;
          esac
          curl -fsSL "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-${COSIGN_ARCH}" -o /usr/local/bin/cosign
          chmod +x /usr/local/bin/cosign
          cosign version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute next tag
        id: version
        shell: bash
        run: |
          set -euo pipefail
          git fetch --tags
          latest=$(git tag -l "v*.*.*" --sort=-v:refname | head -n1)
          if [[ -z "${latest}" ]]; then
            next="v1.0.0"
          else
            IFS='.' read -r v M m <<<"${latest#v}"
            m=$((m+1))
            next="v${v}.${M}.${m}"
          fi
          echo "next=${next}" >> "$GITHUB_OUTPUT"

      - name: Build image for tests (loaded locally)
        run: |
          echo "Building Docker image for testing..."
          for i in {1..3}; do
            echo "Build attempt $i of 3..."
            if docker buildx build \
                --load \
                -t $REGISTRY/${{ steps.repo.outputs.name }}:ci-test \
                .; then
              echo "Docker build completed successfully on attempt $i"
              break
            else
              echo "Docker build failed on attempt $i"
              if [ $i -eq 3 ]; then
                echo "ERROR: All Docker build attempts failed"
                exit 1
              fi
              echo "Retrying in 30 seconds..."
              sleep 30
            fi
          done

      - name: Run hardening + smoke + STIG scan (root for this step only)
        shell: bash
        run: |
          set -euo pipefail
          IMG="$REGISTRY/${{ steps.repo.outputs.name }}:ci-test"

          # Check default image user is non-root (CIS 5.4)
          docker inspect --format '{{.Config.User}}' "$IMG" | grep -Eq '^[0-9]+:[0-9]+$' || {
            echo "::error ::Image default user is not non-root"
            exit 1
          }

          # Warn if AppArmor not available
          sudo aa-status >/dev/null 2>&1 || echo "::warning ::AppArmor not available on host"

          NAME="hardn-test-$$"

          # Run container as root, override entrypoint, keep read-only + tmpfs
          docker run -d --name "$NAME" \
            --entrypoint /bin/bash \
            --user 0:0 \
            --read-only \
            --tmpfs /tmp:rw,noexec,nosuid,mode=1777,size=64m \
            --tmpfs /run:rw,noexec,nosuid,mode=0755,size=16m \
            --tmpfs /home/hardn:rw,mode=0755,size=32m \
            --tmpfs /opt/hardn-xdr:rw,mode=0755,size=64m \
            --pids-limit 256 \
            --cap-drop ALL \
            --security-opt no-new-privileges \
            --security-opt apparmor=docker-default \
            "$IMG" -lc 'sleep infinity'

          # Wait until container is responsive or bail
          for i in {1..30}; do
            if docker exec "$NAME" true 2>/dev/null; then break; fi
            if ! docker ps --format '{{.Names}}' | grep -qx "$NAME"; then
              echo "::error ::Container exited during startup"
              docker logs "$NAME" || true
              docker rm -f "$NAME" >/dev/null 2>&1 || true
              exit 1
            fi
            sleep 2
          done

          echo "[*] Smoke test"
          docker exec "$NAME" bash -lc '/usr/local/bin/smoke_test.sh'

          echo "[*] STIG scan (auto-detect Debian content)"
          CONTENT=$(docker exec "$NAME" bash -lc 'shopt -s nullglob; files=(/usr/share/xml/scap/ssg/content/ssg-debian*-ds.xml); [[ ${#files[@]} -gt 0 ]] && ls -1 ${files[@]} | sort -V | tail -n1 || true')
          if [[ -n "$CONTENT" ]] && docker exec "$NAME" bash -lc 'command -v oscap >/dev/null'; then
            echo "Using content: $CONTENT"
            docker exec "$NAME" bash -lc \
              "oscap xccdf eval \
                 --profile xccdf_org.ssgproject.content_profile_stig \
                 --report /tmp/stig_report.html \
                 --results /tmp/stig_results.xml \
                 \"$CONTENT\" || echo 'STIG scan completed with warnings'"
          else
            echo "STIG content not available; writing placeholders"
            docker exec "$NAME" bash -lc 'echo "<html><body><h1>STIG Scan Not Available</h1></body></html>" > /tmp/stig_report.html'
            docker exec "$NAME" bash -lc 'echo "<?xml version=\"1.0\"?><results><title>STIG Scan Not Available</title></results>" > /tmp/stig_results.xml'
          fi

          mkdir -p artifacts
          docker cp "$NAME":/tmp/stig_report.html artifacts/stig_report.html || true
          docker cp "$NAME":/tmp/stig_results.xml artifacts/stig_results.xml || true

          docker rm -f "$NAME" >/dev/null

      - name: Upload STIG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stig-scan
          path: artifacts/*

      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}
          tags: |
            type=raw,value=deb13
            type=raw,value=${{ steps.version.outputs.next }}
            type=sha

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image (cosign keyless)
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Generate SBOM (Syft) for pushed image@digest
        id: sbom
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}@${{ steps.build-and-push.outputs.digest }}
          format: spdx-json
          artifact-name: sbom-spdx
          output-file: sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom.spdx.json

      - name: Create git tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag ${{ steps.version.outputs.next }}
          git push origin ${{ steps.version.outputs.next }}

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.next }}
          generate_release_notes: true
          files: |
            artifacts/stig_report.html
            artifacts/stig_results.xml
            sbom.spdx.json