name: Docker

on:
  schedule:
    - cron: '27 11 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # may contain uppercase

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # tag + release
      packages: write     # push to GHCR
      security-events: write  # allow SARIF upload
      id-token: write     # cosign keyless

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Normalize image name to lowercase
        id: repo
        run: |
          echo "name=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Install cosign (non-PR)
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Compute next tag (patch bump)
      - name: Compute next tag
        id: version
        shell: bash
        run: |
          set -euo pipefail
          git fetch --tags
          latest=$(git tag -l "v*.*.*" --sort=-v:refname | head -n1)
          if [[ -z "${latest}" ]]; then
            next="v1.0.0"
          else
            IFS='.' read -r v M m <<<"${latest#v}"
            m=$((m+1))
            next="v${v}.${M}.${m}"
          fi
          echo "next=${next}" >> "$GITHUB_OUTPUT"

      # ---------- BUILD (local, for testing) ----------
      - name: Build image for tests (loaded locally)
        run: |
          docker buildx build \
            --load \
            -t $REGISTRY/${{ steps.repo.outputs.name }}:ci-test \
            .

      # ---------- TESTS ----------
      - name: Run hardening + smoke + STIG scan
        run: |
          set -euo pipefail
          IMG="$REGISTRY/${{ steps.repo.outputs.name }}:ci-test"

          CID=$(docker run -d --user 0 --init \
               --read-only --cap-drop ALL --security-opt no-new-privileges \
               --tmpfs /tmp:rw,mode=1777 --tmpfs /run:rw,mode=0755 \
               "$IMG" sleep 600)

          sleep 5

          echo "[*] Smoke test"
          docker exec "$CID" /usr/local/bin/smoke_test.sh

          echo "[*] STIG scan (OpenSCAP)"
          docker exec "$CID" bash -lc \
            'oscap xccdf eval \
               --profile xccdf_org.ssgproject.content_profile_stig \
               --report /tmp/stig_report.html \
               --results /tmp/stig_results.xml \
               /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml || true'

          mkdir -p artifacts
          docker cp "$CID":/tmp/stig_report.html artifacts/stig_report.html || true
          docker cp "$CID":/tmp/stig_results.xml artifacts/stig_results.xml || true

          docker rm -f "$CID" >/dev/null

      - name: Upload STIG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stig-scan
          path: artifacts/*

      # ---------- BUILD & PUSH (final) ----------
      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}
          tags: |
            type=raw,value=rhel9
            type=raw,value=${{ steps.version.outputs.next }}
            type=sha

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---------- SIGN ----------
      - name: Sign the published Docker image (cosign keyless)
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # ---------- SBOM (Syft) ----------
      - name: Generate SBOM (Syft) for pushed image@digest
        id: sbom
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}@${{ steps.build-and-push.outputs.digest }}
          format: spdx-json
          artifact-name: sbom-spdx
          output-file: sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom.spdx.json

      # ---------- Vulnerability Scan (Trivy) ----------
      - name: Trivy vulnerability scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}@${{ steps.build-and-push.outputs.digest }}
          format: 'sarif'
          output: 'trivy.sarif'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'            # fail the job if HIGH/CRITICAL found
          ignore-unfixed: true
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db

      - name: Upload Trivy SARIF to code scanning
        if: always()   # upload even if it failed to allow visibility
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

      - name: Upload Trivy report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy.sarif

      # ---------- TAG & RELEASE ----------
      - name: Create git tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag ${{ steps.version.outputs.next }}
          git push origin ${{ steps.version.outputs.next }}

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.next }}
          generate_release_notes: true
          files: |
            artifacts/stig_report.html
            artifacts/stig_results.xml
            sbom.spdx.json
            trivy.sarif